import os
import uuid
import json
import math
import string
import sqlite3
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Rate Limiting
# ---------------------------------------------------------------------------
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ---------------------------------------------------------------------------
# Database / Audit Log
# ---------------------------------------------------------------------------
DB_PATH = "provenance.db"


def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        CREATE TABLE IF NOT EXISTS audit_log (
            content_id     TEXT PRIMARY KEY,
            creator_id     TEXT,
            timestamp      TEXT,
            attribution    TEXT,
            confidence     REAL,
            llm_score      REAL,
            style_score    REAL,
            label          TEXT,
            status         TEXT DEFAULT 'classified',
            appeal_reason  TEXT,
            appeal_time    TEXT
        )
    """)
    conn.commit()
    conn.close()


def log_submission(content_id, creator_id, attribution, confidence, llm_score, style_score, label):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        INSERT INTO audit_log
            (content_id, creator_id, timestamp, attribution, confidence, llm_score, style_score, label, status)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'classified')
    """, (
        content_id, creator_id,
        datetime.now(timezone.utc).isoformat(),
        attribution, confidence, llm_score, style_score, label
    ))
    conn.commit()
    conn.close()


def log_appeal(content_id, reason):
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("""
        UPDATE audit_log
        SET status = 'under_review',
            appeal_reason = ?,
            appeal_time = ?
        WHERE content_id = ?
    """, (reason, datetime.now(timezone.utc).isoformat(), content_id))
    updated = c.rowcount
    conn.commit()
    conn.close()
    return updated > 0


def get_log(limit=50):
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    c.execute("SELECT * FROM audit_log ORDER BY timestamp DESC LIMIT ?", (limit,))
    rows = [dict(r) for r in c.fetchall()]
    conn.close()
    return rows


def get_entry(content_id):
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    c.execute("SELECT * FROM audit_log WHERE content_id = ?", (content_id,))
    row = c.fetchone()
    conn.close()
    return dict(row) if row else None


# ---------------------------------------------------------------------------
# Signal 1: Groq LLM Classifier
# ---------------------------------------------------------------------------
groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LLM_SYSTEM_PROMPT = """You are an expert forensic linguist specializing in detecting AI-generated text.

Analyze the provided text and determine whether it was likely written by a human or generated by an AI.

Return ONLY a JSON object with no additional text, in exactly this format:
{"score": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}

Where score means:
- 0.0 = definitely human-written
- 0.5 = ambiguous / uncertain
- 1.0 = definitely AI-generated

Key signals to look for:
- AI text: uniform sentence structure, hedged language ("it is important to note"), generic corporate phrasing, symmetrical paragraph structure, lack of personal specificity
- Human text: irregular rhythm, personal anecdotes, typos/informal grammar, strong opinions, idiosyncratic word choices, emotional directness
"""


def llm_classify(text: str) -> tuple[float, str]:
    """Returns (score 0-1, reasoning string). 1 = likely AI."""
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": LLM_SYSTEM_PROMPT},
                {"role": "user", "content": f"Analyze this text:\n\n{text}"}
            ],
            temperature=0.1,
            max_tokens=200,
        )
        raw = response.choices[0].message.content.strip()
        # Strip markdown code fences if present
        raw = raw.replace("```json", "").replace("```", "").strip()
        parsed = json.loads(raw)
        score = float(parsed.get("score", 0.5))
        score = max(0.0, min(1.0, score))
        reasoning = parsed.get("reasoning", "")
        return score, reasoning
    except Exception as e:
        # Fallback to 0.5 (uncertain) if LLM call fails
        return 0.5, f"LLM signal unavailable: {str(e)}"


# ---------------------------------------------------------------------------
# Signal 2: Stylometric Heuristics
# ---------------------------------------------------------------------------

def stylometric_score(text: str) -> float:
    """
    Returns a score 0-1 where 1 = patterns consistent with AI generation.
    Measures: sentence length variance, type-token ratio, punctuation density.
    """
    import re

    # Split into sentences (simple heuristic)
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    sentences = [s for s in sentences if len(s.strip()) > 0]

    if len(sentences) < 2:
        # Not enough data — return neutral
        return 0.5

    # --- Metric 1: Sentence length variance ---
    # AI text tends to have lower variance (more uniform lengths)
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    # Normalize: std_dev < 3 is very uniform (AI-like); > 10 is highly variable (human-like)
    # Invert so high score = AI-like
    variance_score = max(0.0, min(1.0, 1.0 - (std_dev / 12.0)))

    # --- Metric 2: Type-Token Ratio (vocabulary diversity) ---
    words = re.findall(r'\b[a-zA-Z]+\b', text.lower())
    if len(words) == 0:
        ttr_score = 0.5
    else:
        ttr = len(set(words)) / len(words)
        # AI text: TTR often 0.55–0.70; human text varies more but casual human = lower TTR
        # High uniformity of *word repetition* at specific levels suggests AI
        # We flag mid-high TTR as potentially AI; very high or very low = human
        # Simple heuristic: TTR in [0.55, 0.80] → AI-like
        if 0.55 <= ttr <= 0.80:
            ttr_score = 0.6
        elif ttr > 0.80:
            ttr_score = 0.3  # very diverse vocab = likely human or technical
        else:
            ttr_score = 0.4  # repetitive casual text = likely human

    # --- Metric 3: Punctuation density / diversity ---
    # Humans use em-dashes, ellipses, exclamation marks, parentheses more idiosyncratically
    human_punct = set("—…!?();")
    punct_chars = [c for c in text if c in string.punctuation]
    human_punct_count = sum(1 for c in text if c in human_punct)
    total_chars = max(len(text), 1)
    human_punct_density = human_punct_count / total_chars
    # Low human punctuation density → more AI-like
    punct_score = max(0.0, min(1.0, 1.0 - (human_punct_density * 30)))

    # Combine three metrics equally
    combined = (variance_score * 0.45) + (ttr_score * 0.30) + (punct_score * 0.25)
    return round(combined, 4)


# ---------------------------------------------------------------------------
# Confidence Scoring
# ---------------------------------------------------------------------------

def compute_confidence(llm_score: float, style_score: float) -> float:
    """Weighted combination. LLM signal weighted 65%, stylometric 35%."""
    return round((0.65 * llm_score) + (0.35 * style_score), 4)


def attribution_label(confidence: float) -> str:
    if confidence >= 0.65:
        return "likely_ai"
    elif confidence <= 0.35:
        return "likely_human"
    else:
        return "uncertain"


# ---------------------------------------------------------------------------
# Transparency Label
# ---------------------------------------------------------------------------

def transparency_label(attribution: str, confidence: float) -> str:
    pct = round(confidence * 100)
    if attribution == "likely_ai":
        return (
            f"⚠️ AI-Generated Content Detected\n"
            f"Our analysis found strong signals that this content was likely generated by an AI tool. "
            f"Confidence: {pct}%\n"
            f"This label is based on automated analysis and may not be perfect. "
            f"If you are the author and believe this is incorrect, you can submit an appeal."
        )
    elif attribution == "likely_human":
        return (
            f"✅ Likely Human-Written\n"
            f"Our analysis found strong signals that this content was written by a human author. "
            f"Confidence: {pct}%\n"
            f"Automated analysis is not perfect. This label reflects our best assessment based on available signals."
        )
    else:
        return (
            f"🔍 Authorship Unclear\n"
            f"Our system could not determine with confidence whether this content was written by a human "
            f"or generated by AI. It will be treated as unverified. "
            f"Confidence: {pct}%\n"
            f"If you are the author, you may submit an appeal to provide context about your writing process."
        )


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(force=True)
    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "anonymous")

    if not text:
        return jsonify({"error": "text field is required"}), 400
    if len(text) < 10:
        return jsonify({"error": "text is too short for analysis"}), 400

    content_id = str(uuid.uuid4())

    # Run both signals
    llm_score, llm_reasoning = llm_classify(text)
    style_score = stylometric_score(text)

    # Combine into confidence
    confidence = compute_confidence(llm_score, style_score)
    attribution = attribution_label(confidence)
    label = transparency_label(attribution, confidence)

    # Write to audit log
    log_submission(content_id, creator_id, attribution, confidence, llm_score, style_score, label)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "confidence_pct": round(confidence * 100),
        "llm_score": llm_score,
        "style_score": style_score,
        "llm_reasoning": llm_reasoning,
        "label": label,
        "status": "classified"
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(force=True)
    content_id = data.get("content_id", "").strip()
    reasoning = data.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "content_id is required"}), 400
    if not reasoning:
        return jsonify({"error": "creator_reasoning is required"}), 400

    entry = get_entry(content_id)
    if not entry:
        return jsonify({"error": "content_id not found"}), 404

    if entry.get("status") == "under_review":
        return jsonify({"error": "an appeal is already pending for this content"}), 409

    success = log_appeal(content_id, reasoning)
    if not success:
        return jsonify({"error": "failed to record appeal"}), 500

    return jsonify({
        "content_id": content_id,
        "status": "appeal_received",
        "message": "Your appeal has been recorded and the content is now under review. A human reviewer will assess your submission.",
        "original_attribution": entry.get("attribution"),
        "original_confidence": entry.get("confidence"),
    })


@app.route("/log", methods=["GET"])
def view_log():
    limit = request.args.get("limit", 50, type=int)
    entries = get_log(limit)
    return jsonify({"count": len(entries), "entries": entries})


@app.route("/status/<content_id>", methods=["GET"])
def status(content_id):
    entry = get_entry(content_id)
    if not entry:
        return jsonify({"error": "content_id not found"}), 404
    return jsonify(entry)


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"})


# ---------------------------------------------------------------------------
# Entry Point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    init_db()
    app.run(debug=True, port=5000)
